# -*- coding: utf-8 -*-
"""Single source of truth for demo content. Emitted into HTML and into assets/js data files."""

SITE = dict(
    name='Standform', legal='Standform Exhibition Studio', url='https://www.standform.example',
    phone='+1 (312) 555-0142', phone_raw='+13125550142', email='hello@standform.example',
    address='1200 Expo Drive, Suite 300, Chicago, IL 60607, USA', hours='Mon-Fri 8:00-18:00 CT',
)

INDUSTRIES = [('technology', 'Technology'), ('healthcare', 'Healthcare'), ('automotive', 'Automotive'), ('manufacturing', 'Manufacturing'),
              ('retail', 'Retail'), ('finance', 'Finance'), ('food-beverage', 'Food & Beverage')]

CATEGORIES = [('all', 'All'), ('custom-booth', 'Custom Booths'), ('rental', 'Rental Stands'), ('island-booth', 'Island Booths'), ('inline-booth', 'Inline Booths'),
              ('peninsula-booth', 'Peninsula Booths'), ('double-decker', 'Double-Decker'), ('pavilion', 'Pavilions')]

PROJECTS = [
    dict(slug='novatech-island-booth', n=1, title='NovaTech Exhibition Stand', type='island', typeLabel='Custom Island Booth', mode='custom', industry='technology',
         size='40 × 30 ft', sqft=1200, event='TechForward Expo 2025', location='Las Vegas, NV', year=2025,
         desc='A four-sided island with a ring-truss canopy, dual LED walls and a central product tower that pulls visitors in from every aisle.',
         challenge='NovaTech launched a new edge-computing line and needed one stand that worked for press briefings, live demos and quiet one-to-one meetings, all without a back wall to hide storage or hospitality.',
         solution='We split the 1,200 sq ft footprint into three zones around a monolithic product tower: a demo perimeter, a briefing counter cluster and a hidden meeting pod. A 12 m ring truss carries the brand at eye-level from every direction.',
         materials=['Powder-coated steel frame', 'Laminated MDF panels', 'Tempered acrylic', 'Low-pile modular carpet tiles'],
         lighting='Warm 3000 K accent washes on the tower, cool 5000 K on the LED walls, and a dimmable ring truss with 48 LED profile spots.',
         branding='Large-format dye-sublimated fabric on the ring, 3 mm vinyl on the tower and a single accent orange used only on interactive zones.',
         construction='Prefabricated in 14 modules at our Chicago workshop and pre-assembled once for a full dry-fit before shipping.',
         install='Six-person crew, 3 days on site including electrical sign-off; dismantle in 14 hours.',
         results=[('1,900+', 'Badge scans over three days'), ('62', 'Booked one-to-one meetings'), ('3 days', 'On-site installation')]),
    dict(slug='kite-modular-rental-stand', n=2, title='Kite Launch Stand', type='inline', typeLabel='Rental Inline Stand', mode='rental', industry='technology',
         size='20 × 10 ft', sqft=200, event='Launchpad Startup Summit', location='Austin, TX', year=2025,
         desc='A rental kit dressed with custom graphics: five modular panels, a branded counter and a product shelf, ready in a single shift.',
         challenge='A Series A startup had six weeks, one small budget and a need to look established next to much larger exhibitors.',
         solution='We configured our rental panel system with a stepped colour rhythm, a custom fascia and a back-lit product shelf, then reused the kit at two more shows.',
         materials=['Rental aluminium extrusion frame', 'Printed SEG fabric panels', 'Rental counter and shelf', 'Colour-matched floor tiles'],
         lighting='Four clip-on LED arms with warm-white spots and a backlit logo panel.',
         branding='Tension-fabric graphics reprinted between shows; only the fascia and counter wrap were custom.',
         construction='Rental kit re-finished and quality-checked before dispatch; custom graphics printed in-house.',
         install='Two installers, four hours; dismantle in 90 minutes.',
         results=[('4 hrs', 'Installation time'), ('3 shows', 'Kit reused in one year'), ('38%', 'Lower cost than a comparable custom build')]),
    dict(slug='meridian-health-pavilion', n=3, title='Meridian Health Pavilion', type='pavilion', typeLabel='Custom Pavilion', mode='custom', industry='healthcare',
         size='60 × 40 ft', sqft=2400, event='MedLink Congress', location='Düsseldorf, Germany', year=2024,
         desc='A calm, clinical pavilion that shelters three product zones under one white canopy frame and a central consultation hub.',
         challenge='Meridian needed a large-format presence that felt reassuring and scientific rather than commercial, and had to stay compliant with strict hall fire-safety and material rules.',
         solution='A continuous white canopy frame unifies three zone walls in tonal teal. Materials were selected for low-flame-spread certification and a circular hub keeps conversations private but visible.',
         materials=['Fire-retardant treated timber', 'Solid-surface counters', 'Frosted acrylic', 'Wool-blend carpet'],
         lighting='High-CRI diffuse lighting at 4000 K to keep product colour honest, with soft uplighting on the canopy fascia.',
         branding='Restrained two-colour identity with product photography reserved for the zone walls.',
         construction='Built in Chicago, shipped in 11 crates by sea freight, with local partner crew for hall connection.',
         install='Eight-person crew, 4 days including hall-supplied power and rigging inspections.',
         results=[('3', 'Product zones in one footprint'), ('4 days', 'Install including inspections'), ('0', 'Compliance findings at hall sign-off')]),
    dict(slug='curalis-rental-inline', n=4, title='Curalis Diagnostics Stand', type='inline', typeLabel='Rental Inline Stand', mode='rental', industry='healthcare',
         size='10 × 20 ft', sqft=200, event='Clinical Innovations Forum', location='Boston, MA', year=2025,
         desc='A bright rental inline with a bold circular brand motif, a demo counter and two consultation seats.',
         challenge='A diagnostics start-up needed a credible medical look in a shared hall with strict height limits.',
         solution='We kept everything under the 12 ft limit, used a single circular graphic as the hero and specified rental furniture in matching teal.',
         materials=['Rental panel system', 'Printed graphic panels', 'Rental counter and stools', 'Grey carpet tiles'],
         lighting='Two overhead LED tracks and a soft-glow counter front.',
         branding='One large circle, one colour, a single headline.',
         construction='Rental kit with custom-printed panels and a bespoke counter wrap.',
         install='Two installers, five hours.',
         results=[('5 hrs', 'Installation time'), ('12 ft', 'Height-limit compliance'), ('1', 'Kit, reused twice')]),
    dict(slug='vantage-motors-double-decker', n=5, title='Vantage Motors Showcase', type='double-decker', typeLabel='Double-Decker Stand', mode='custom', industry='automotive',
         size='50 × 40 ft', sqft=2000, event='AutoVision International', location='Detroit, MI', year=2024,
         desc='A two-storey showcase with a turntable vehicle stage on the ground floor and a glass-fronted hospitality lounge above.',
         challenge='The brand wanted a hero vehicle visible from across the hall and a private space to host dealers, without losing floor area for the public.',
         solution='The upper deck cantilevers over the rear half so the turntable stays open to the aisle. A glass balustrade gives the lounge a view of the show floor.',
         materials=['Structural steel deck frame', 'Laminated glass balustrade', 'Gloss-lacquered panels', 'Resin flooring'],
         lighting='Overhead ring with tunable white, low-glare uplighting on the vehicle and warm ambient light in the lounge.',
         branding='Illuminated fascia lettering and full-height LED wall in brand red.',
         construction='Deck structure engineered with a certified structural engineer and load-tested before shipping.',
         install='Twelve-person crew, 6 days with crane and lift support; dismantle in 3 days.',
         results=[('2 levels', '2,000 sq ft of usable area'), ('84', 'Dealer meetings hosted upstairs'), ('6 days', 'On-site build')]),
    dict(slug='torque-ev-island', n=6, title='Torque EV Charging Island', type='island', typeLabel='Custom Island Booth', mode='custom', industry='automotive',
         size='40 × 40 ft', sqft=1600, event='Electric Mobility Show', location='Los Angeles, CA', year=2025,
         desc='A circular stage under a halo ring, four illuminated pylons and working demonstration chargers.',
         challenge='Torque needed to show real hardware working, and to make a quiet product feel dramatic.',
         solution='A raised circular plinth places the vehicle at the centre, ringed by four light pylons that mark the corners and the queue. Live chargers sit on the perimeter.',
         materials=['Curved plywood plinth', 'Aluminium pylons with LED strip', 'Polished concrete-effect vinyl', 'Rental charging hardware'],
         lighting='Green-white halo ring on a dimming loop, plus programmed pylon animation tied to the product demo.',
         branding='Minimal wordmark on pylons and a single line of copy.',
         construction='CNC-cut plinth segments assembled on site around the vehicle.',
         install='Eight installers, 3 days; power tested with the hall electrician.',
         results=[('4', 'Live charging demos'), ('3 days', 'Installation'), ('1', 'Halo ring seen across the hall')]),
    dict(slug='ironbridge-industrial-peninsula', n=7, title='Ironbridge Automation Peninsula', type='peninsula', typeLabel='Custom Peninsula Booth', mode='custom', industry='manufacturing',
         size='30 × 20 ft', sqft=600, event='Industrial Automation Expo', location='Hannover, Germany', year=2024,
         desc='A working robot cell and conveyor line behind a safety frame, with a hazard-striped floor that doubles as wayfinding.',
         challenge='Real machinery had to run safely in public with heavy floor loads and an enclosed cell, while still feeling open to visitors.',
         solution='A structural frame guards the cell without hiding it, while a striped floor guides visitors to the demo counter and the meeting table.',
         materials=['Steel safety frame', 'Reinforced deck panels', 'Powder-coated aluminium', 'Anti-fatigue flooring'],
         lighting='High-output task lighting on the cell, softer light in the meeting zone.',
         branding='Industrial yellow on charcoal, one clear headline on a 9 m fascia.',
         construction='Deck reinforced for 1.5 tonnes per square metre point loads.',
         install='Five-person crew, 2 days; machinery placed by hall riggers.',
         results=[('1.5 t/m²', 'Reinforced deck rating'), ('2 days', 'Installation'), ('0', 'Safety findings')]),
    dict(slug='solara-energy-island', n=8, title='Solara Solar Island', type='island', typeLabel='Custom Island Booth', mode='custom', industry='manufacturing',
         size='30 × 30 ft', sqft=900, event='CleanPower Expo', location='Houston, TX', year=2025,
         desc='Tilted live solar panels, timber slat walls and planted corners that make a sustainability story physical.',
         challenge='A solar manufacturer wanted to demonstrate its product outdoors-in-a-hall without any greenwashing.',
         solution='We built the booth from reclaimable parts: FSC timber slat walls, a demountable deck and real panels wired to a live output display.',
         materials=['FSC-certified timber slats', 'Modular reclaimable deck', 'Live solar panels', 'Recycled-content carpet'],
         lighting='LED fixtures powered from a bank of the on-stand panels for the demonstration.',
         branding='Natural finishes with a single green accent; printed on recycled substrates.',
         construction='90% of the structure returned to stock after the show.',
         install='Six-person crew, 3 days; strike and return in 10 hours.',
         results=[('90%', 'Structure reused after the show'), ('3 days', 'Installation'), ('1', 'Live energy display')]),
    dict(slug='lumen-retail-inline', n=9, title='Lumen Lighting Boutique', type='inline', typeLabel='Custom Inline Booth', mode='custom', industry='retail',
         size='10 × 20 ft', sqft=200, event='RetailNext Summit', location='New York, NY', year=2025,
         desc='A neon-signed retail wall with plinths and product shelving that turns a 200 sq ft inline into a lit-product gallery.',
         challenge='A lighting brand had a very small inline space and needed to show light quality, not just products.',
         solution='A dark back wall lets the products glow, with graduated shelf heights and one signature neon.',
         materials=['Matt black laminated panels', 'Custom neon-effect LED', 'Solid-surface plinths', 'Dark grey carpet'],
         lighting='Every product self-lit, everything else kept dark, 2700 K counter and one coloured accent.',
         branding='One neon wordmark; no other graphics.',
         construction='Wall and shelving fabricated in three sections for one-person handling.',
         install='Three installers, one day.',
         results=[('1 day', 'Installation'), ('1', 'Signature neon'), ('200 sq ft', 'Footprint')]),
    dict(slug='nordic-design-collective-pavilion', n=10, title='Nordic Design Collective', type='pavilion', typeLabel='Rental Pavilion', mode='rental', industry='retail',
         size='40 × 30 ft', sqft=1200, event='Nordic Design Week', location='Stockholm, Sweden', year=2024,
         desc='A rental frame system that divides one hall space into four exhibitor bays with a shared fascia and a light timber palette.',
         challenge='Four independent designers needed one shared identity and individual spaces, on a modest budget.',
         solution='We used a rental frame with four pastel wall inserts, a common fascia and matching plinths, so each exhibitor could style their own bay.',
         materials=['Rental frame system', 'Fabric wall inserts', 'Birch plywood plinths', 'Natural-fibre carpet'],
         lighting='Overhead track spots, adjustable per bay.',
         branding='Shared typographic fascia, individual bay graphics.',
         construction='Fully rental kit with bespoke graphics.',
         install='Six installers, 2 days.',
         results=[('4', 'Independent exhibitors in one pavilion'), ('2 days', 'Installation'), ('100%', 'Frame system returned to stock')]),
    dict(slug='halcyon-capital-double-decker', n=11, title='Halcyon Capital Lounge', type='double-decker', typeLabel='Double-Decker Stand', mode='custom', industry='finance',
         size='30 × 30 ft', sqft=900, event='FinServ Global Forum', location='London, UK', year=2024,
         desc='A glass-fronted upper lounge with a ground-floor reception, in restrained navy and brass.',
         challenge='A wealth manager wanted a private, discreet setting for client conversations in the middle of a busy show hall.',
         solution='The upper level is a glazed lounge with acoustic panelling, while the ground floor works as a welcoming reception with a brass-topped counter.',
         materials=['Acoustic panel walls', 'Laminated glass', 'Brass-effect laminate', 'Wool carpet'],
         lighting='Warm layered lighting; dimmable pendants in the lounge.',
         branding='Wordmark in brass on navy, no product imagery.',
         construction='Pre-built at 1:1 for acoustic testing.',
         install='Eight crew, 4 days.',
         results=[('18 dB', 'Measured noise reduction in lounge'), ('4 days', 'Installation'), ('2', 'Levels of hospitality')]),
    dict(slug='harvest-and-hearth-peninsula', n=12, title='Harvest & Hearth Food Booth', type='peninsula', typeLabel='Custom Peninsula Booth', mode='custom', industry='food-beverage',
         size='30 × 20 ft', sqft=600, event='FoodTech Expo', location='Chicago, IL', year=2025,
         desc='A working sampling kitchen with a timber slat wall, hanging pendants and a bar counter that keeps the queue moving.',
         challenge='A food brand needed to sample daily to thousands of visitors, safely and with a queue that felt like part of the show.',
         solution='An L-shaped counter separates preparation from service, and a slat wall gives the brand a warm, tactile backdrop.',
         materials=['Food-safe solid surface counters', 'Timber slat wall', 'Washable flooring', 'Stainless service equipment'],
         lighting='Warm pendants at counter height, cool task lighting in the kitchen.',
         branding='Painted timber lettering and a menu board updated every day.',
         construction='Plumbing and power pre-planned with the hall for a water-safe layout.',
         install='Six installers, 3 days including plumbing sign-off.',
         results=[('4,200', 'Samples served across the show'), ('3 days', 'Installation'), ('0', 'Hygiene findings')]),
]
for p in PROJECTS:
    p['img'] = 'project-%02d' % p['n']
    p['industryLabel'] = dict(INDUSTRIES)[p['industry']]

SERVICES = [
    dict(slug='custom-booth-design', n=1, title='Custom Booth Design', icon='i-ruler',
         desc='Concepts, 3D renders and technical drawings that turn your brand and goals into a floor plan people want to walk into.',
         benefits=['Brand-first spatial planning', 'Photo-real 3D renders', 'Show-rule compliant drawings'],
         tagline='Spatial design that starts with your goals, not a catalogue.',
         overview='Every custom stand starts with a conversation about who you want to reach and what you want them to do. We turn that into a plan, a 3D model and a set of build-ready drawings that respect hall rules, your budget and your timeline.',
         includes=['Discovery workshop', 'Concept sketches and mood boards', '3D renders from two camera angles', 'Floor plan and elevations', 'Materials and finishes board', 'Show-rule and hall compliance check'],
         deliverables=['Design presentation (PDF)', '3D model and render set', 'Technical drawing pack', 'Bill of quantities', 'Show-kit compliance forms'],
         price=('From $95 / sq ft', 'Design fee is included with construction and quoted separately as a fixed fee for design-only projects.',
                [('Concept design only', 'From $2,400 fixed'), ('Concept + 3D + drawings', 'From $6,800 fixed'), ('Design credited against build', '100% credited')])),
    dict(slug='exhibition-stand-construction', n=2, title='Exhibition Stand Construction', icon='i-hammer',
         desc='Precision fabrication in our own workshop: carpentry, metalwork, finishing and pre-assembly before anything ships.',
         benefits=['In-house workshop', 'Full dry-fit before shipping', 'Reusable, modular builds'],
         tagline='Built like architecture, finished like a product.',
         overview='Our 42,000 sq ft workshop in Chicago houses carpentry, CNC, metalwork, paint and pre-assembly. Nothing ships until we have built your stand once, checked every joint and photographed it for your approval.',
         includes=['CNC cutting and joinery', 'Steel and aluminium fabrication', 'Spray finishing', 'Electrical pre-wiring', 'Full pre-assembly', 'Crating and packing lists'],
         deliverables=['Pre-shipment photo report', 'Assembly manual', 'Load and safety certificates', 'Crate manifest', 'Reuse and storage plan'],
         price=('From $95 / sq ft', 'Custom builds are quoted per square foot with a fixed scope; large structures and double-decker builds are quoted per project.',
                [('Inline 10 × 10 to 10 × 20', '$95 - $150 / sq ft'), ('Island 20 × 20 and above', '$145 - $230 / sq ft'), ('Double-decker', '$170 - $260 / sq ft of footprint')])),
    dict(slug='rental-exhibition-stands', n=3, title='Rental Exhibition Stands', icon='i-layers',
         desc='Engineered rental systems finished with your graphics and furniture. Faster, lighter on budget, better for the planet.',
         benefits=['Up to 40% lower cost', 'Ready in as little as 3 weeks', 'Reusable systems'],
         tagline='Premium rental stands that don\'t look like rentals.',
         overview='Our rental range is built on a proprietary panel and frame system. We configure it to your footprint, add custom graphics, counters and lighting, and collect it after the show for reuse, so you pay for the days you need it.',
         includes=['Configured layout and render', 'Panel, frame and fascia system', 'Rental counters, furniture and screens', 'Custom graphics', 'Delivery, installation and dismantle', 'Storage of graphics for the next show'],
         deliverables=['Layout drawing', 'Graphic proof sheet', 'Rental agreement', 'On-site installation', 'Post-show report'],
         price=('From $42 / sq ft', 'Rental pricing covers one show. Multi-show contracts and graphic storage lower the per-show cost.',
                [('10 × 10 inline', 'From $4,200'), ('20 × 20 island', 'From $22,000'), ('Multi-show agreement', 'Up to 15% less per show')])),
    dict(slug='booth-installation', n=4, title='Booth Installation', icon='i-truck',
         desc='Experienced installation crews and supervisors who know the halls, the unions and the tight timelines.',
         benefits=['Certified supervisors', 'Multi-city crews', 'Daily progress reports'],
         tagline='Set-up done right the first time, on schedule.',
         overview='Our installation teams work in more than 60 exhibition venues and know each hall\'s rules, labour arrangements and rigging requirements. A named supervisor is on site from first crate to final sign-off.',
         includes=['Freight and drayage coordination', 'Union and venue labour management', 'Rigging and electrical coordination', 'On-site supervisor', 'Final quality walk-through', 'Daily progress photos'],
         deliverables=['Install schedule', 'Site risk assessment', 'Progress reports', 'Handover checklist', 'Emergency contact sheet'],
         price=('From $12 / sq ft', 'Installation pricing depends on venue labour rules, the number of days and the complexity of the build.',
                [('Standard inline', 'From $1,800'), ('Island build', 'From $6,500'), ('Complex or multi-level', 'Quoted per project')])),
    dict(slug='booth-dismantling', n=5, title='Booth Dismantling', icon='i-box',
         desc='Fast, careful teardown, crating and return so your stand is ready for the next show, or for storage.',
         benefits=['Careful, labelled teardown', 'Reuse-first approach', 'Storage and refurbishment'],
         tagline='Strike smart, and get more shows from every build.',
         overview='The show ends and the clock starts. We take the stand down in a planned order, crate every part with labels, dispose of waste responsibly and return reusable components to our workshop for inspection and storage.',
         includes=['Teardown plan', 'Labelled crating', 'Freight booking', 'Waste and recycling handling', 'Post-show inspection', 'Storage and refurbishment quote'],
         deliverables=['Strike schedule', 'Crate manifest', 'Damage report', 'Recycling record', 'Refurbishment quote'],
         price=('From $4 / sq ft', 'Dismantling is priced with installation for most projects and separately for third-party stands.',
                [('Inline dismantle', 'From $900'), ('Island dismantle', 'From $2,800'), ('Storage per crate / month', 'From $18')])),
    dict(slug='graphic-branding-production', n=6, title='Graphic & Branding Production', icon='i-printer',
         desc='Large-format printing, fabric graphics and signage produced in-house, with colour proofing that matches your brand.',
         benefits=['In-house large-format print', 'Brand colour matching', 'Fast reprints'],
         tagline='Your brand, printed at a scale that stops people.',
         overview='Colour drift and last-minute artwork changes are the classic exhibition headaches. Our in-house print studio proofs to your brand colours and turns around corrections in hours, not days.',
         includes=['Pre-flight artwork check', 'Colour-matched proofing', 'Fabric, vinyl and rigid substrates', 'Backlit and SEG systems', 'Dimensional lettering', 'Fit-check before shipping'],
         deliverables=['Artwork templates', 'Proof approvals', 'Printed graphics', 'Spare set on request', 'Graphic storage plan'],
         price=('From $6 / sq ft', 'Graphic pricing depends on substrate, finish and size. Reprints are discounted.',
                [('Fabric graphic (SEG)', 'From $11 / sq ft'), ('Vinyl on panel', 'From $6 / sq ft'), ('Dimensional letters', 'From $85 each')])),
    dict(slug='lighting-and-electrical', n=7, title='Lighting & Electrical', icon='i-bulb',
         desc='Lighting design and certified electrical work that makes your products look right and keeps everything compliant.',
         benefits=['Certified electricians', 'High-CRI product lighting', 'Hall-compliant power plans'],
         tagline='Light your story, keep the power on.',
         overview='Good lighting is the cheapest upgrade a stand can have. We design layouts around what you want people to see, specify efficient fixtures and coordinate with the hall electrician so the power supply is right from day one.',
         includes=['Lighting concept and layout', 'Fixture selection', 'Power load calculation', 'Hall power orders', 'Certified electrical installation', 'Testing and tagging'],
         deliverables=['Lighting plan', 'Power schedule', 'Test certificates', 'Fixture list', 'Emergency procedures'],
         price=('From $5 / sq ft', 'Lighting is quoted with the stand design; power orders are billed at hall rates plus coordination.',
                [('Standard lighting package', 'From $5 / sq ft'), ('Feature lighting (ring, LED wall)', 'From $18 / sq ft'), ('Hall power orders', 'At cost + 10%')])),
    dict(slug='project-management', n=8, title='Project Management', icon='i-clipboard',
         desc='One accountable project manager from brief to strike: schedules, suppliers, freight and on-site coordination.',
         benefits=['One point of contact', 'Shared schedule and budget', 'Multi-show planning'],
         tagline='One team, one plan, no last-minute surprises.',
         overview='Exhibitions involve dozens of suppliers and dozens of deadlines. Your project manager owns the plan, the budget and the risk register, and gives you a weekly summary so you always know what is happening.',
         includes=['Critical-path schedule', 'Budget tracking', 'Supplier and freight coordination', 'Show-kit deadlines', 'Weekly status updates', 'Post-show review'],
         deliverables=['Project plan', 'Budget report', 'Risk register', 'Weekly status notes', 'Lessons-learned review'],
         price=('From 8% of project value', 'Project management is included with full-service projects and offered as a stand-alone service for existing builds.',
                [('Full-service project', 'Included'), ('Stand-alone (per show)', 'From $2,500'), ('Multi-show programme', 'From $1,900 / show')])),
]
for s in SERVICES:
    s['img'] = 'service-%02d' % s['n']

BOOTH_TYPES = [
    dict(slug='island', name='Island Booths', plan='plan-island', size='20 × 20 to 60 × 60 ft', open_='4 open sides',
         ideal='Brands that want maximum visibility and a 360° experience in the middle of the hall.',
         layout='Free-standing footprint with aisles on all four sides, no shared walls.',
         benefits=['Visible from every direction', 'Room for demos, meeting areas and hospitality', 'Hanging signs allowed in most halls'],
         custom=['Ring or grid truss overhead', 'Two-level meeting rooms', 'Interactive product zones'], filter='island-booth'),
    dict(slug='peninsula', name='Peninsula Booths', plan='plan-peninsula', size='20 × 20 to 40 × 40 ft', open_='3 open sides',
         ideal='Exhibitors who want strong exposure with a back wall for storage, graphics and screens.',
         layout='Attached to a neighbour at the back with aisles on three sides.',
         benefits=['Excellent aisle exposure', 'Hidden storage and hospitality behind the wall', 'Good balance of budget and impact'],
         custom=['Full-height feature wall', 'Corner reception counter', 'Private meeting room'], filter='peninsula-booth'),
    dict(slug='inline', name='Inline Booths', plan='plan-inline', size='10 × 10 to 10 × 30 ft', open_='1 open side',
         ideal='First-time exhibitors and lean teams who need a professional presence on a defined budget.',
         layout='In a row between neighbours with one aisle-facing front.',
         benefits=['Lower cost per show', 'Easy to install and transport', 'Simple, focused message'],
         custom=['Custom counter and fascia', 'Backlit graphics', 'Product plinths and shelving'], filter='inline-booth'),
    dict(slug='corner', name='Corner Booths', plan='plan-corner', size='10 × 10 to 20 × 20 ft', open_='2 open sides',
         ideal='Brands wanting more exposure than an inline for only a small step up in cost.',
         layout='At the end of a row with aisles on two adjacent sides.',
         benefits=['Two-sided visibility', 'Angled sightlines from two aisles', 'Efficient use of floor area'],
         custom=['Angled reception', 'Wraparound graphic wall', 'Small demo station'], filter='custom-booth'),
    dict(slug='modular', name='Modular Booths', plan='plan-modular', size='10 × 10 to 30 × 30 ft', open_='1 - 4 open sides',
         ideal='Teams that exhibit at multiple shows and need one system that reconfigures for any footprint.',
         layout='Standard panel and frame grid reconfigurable per show.',
         benefits=['Reusable across shows', 'Fast installation', 'Lower total cost over time'],
         custom=['Custom fascia and counter', 'Interchangeable graphics', 'Add-on meeting rooms'], filter='custom-booth'),
    dict(slug='double-decker', name='Double-Decker Stands', plan='plan-double-decker', size='30 × 30 to 60 × 40 ft', open_='2 levels',
         ideal='Large exhibitors who need private hospitality space without giving up ground floor exposure.',
         layout='Structural upper deck with stairs and a glazed balustrade.',
         benefits=['Doubles usable area', 'Private meeting and hospitality space', 'Landmark presence in the hall'],
         custom=['Glazed lounge', 'Feature staircase', 'Roof terrace or sign'], filter='double-decker'),
    dict(slug='pavilion', name='Custom Pavilions', plan='plan-pavilion', size='40 × 30 ft and above', open_='Multi-exhibitor',
         ideal='Trade bodies, regions and consortia who need one identity over many exhibitors.',
         layout='Shared structure with individual bays and a communal hub.',
         benefits=['One identity for many exhibitors', 'Shared cost, shared power', 'Flexible bay sizes'],
         custom=['Central hub', 'Shared fascia and gateway', 'Per-exhibitor styling'], filter='pavilion'),
    dict(slug='rental', name='Rental Stands', plan='plan-rental', size='10 × 10 to 40 × 40 ft', open_='Any layout',
         ideal='Teams who want a professional stand for a single show, or trial a footprint before investing.',
         layout='Pre-engineered kit in any footprint, finished with custom graphics.',
         benefits=['Lower up-front cost', 'Shorter lead time', 'No storage or refurbishment'],
         custom=['Custom graphics', 'Rental counters and furniture', 'Extra lighting'], filter='rental'),
]

PROCESS = [
    ('Project Discovery', 'We start with the business case: who you need to reach, what you want them to do and what success looks like.',
     ['Brand and audience', 'Event, hall and booth size', 'Goals and KPIs', 'Budget and timeline'], '1 week'),
    ('Concept & Strategy', 'Layout options, visitor flow and a creative direction, tested against your goals before anything is drawn in detail.',
     ['Two concept routes', 'Visitor-flow diagram', 'Materials palette'], '1 - 2 weeks'),
    ('3D Booth Design', 'Photo-real 3D models, floor plans and elevations that show exactly what you will get.',
     ['3D renders', 'Floor plan and elevations', 'Lighting concept'], '2 weeks'),
    ('Client Approval', 'A clear sign-off pack with fixed scope, schedule and price so there are no surprises later.',
     ['Design sign-off', 'Fixed-scope quote', 'Show-kit checklist'], '1 week'),
    ('Fabrication & Production', 'Our workshop builds, finishes and pre-wires every element, and we assemble the stand once before shipping.',
     ['Workshop build', 'Full dry-fit', 'Photo report'], '4 - 8 weeks'),
    ('Graphics & Branding', 'Colour-proofed large-format graphics and signage, produced in-house and fitted to the stand.',
     ['Colour proofs', 'Large-format print', 'Fit check'], 'Runs alongside build'),
    ('Logistics & Delivery', 'Crating, freight, customs paperwork and hall scheduling handled by one logistics lead.',
     ['Crate manifest', 'Freight and customs', 'Hall delivery slot'], '1 - 2 weeks'),
    ('On-Site Installation', 'Named supervisors and crews install, connect power and sign off with the hall.',
     ['Supervised install', 'Power and rigging', 'Final walk-through'], '2 - 6 days'),
    ('Event Support', 'A technician stays on call throughout the show for repairs, changes and hall queries.',
     ['On-site technician', 'Daily cleaning check', 'Rapid repairs'], 'Show duration'),
    ('Dismantling', 'Careful teardown, labelled crating, recycling and return or storage for the next show.',
     ['Strike plan', 'Waste and recycling', 'Storage quote'], '1 - 2 days'),
]

TESTIMONIALS = [
    dict(q='Standform turned a vague brief into a stand our sales team could actually work from. The install went smoothly and the hall inspector had nothing to flag.', name='Priya Raman', role='VP Marketing', company='NovaTech Systems', industry='Technology', ctx='TechForward Expo 2025 - 40 × 30 ft island'),
    dict(q='They understood the compliance side of a medical show before we did. The pavilion felt calm and confident, which is exactly what our brand needed.', name='Dr. Lukas Weber', role='Head of Events', company='Meridian Health', industry='Healthcare', ctx='MedLink Congress - 60 × 40 ft pavilion'),
    dict(q='Two-storey stand, tight schedule, one project manager who always picked up the phone. That is what made the difference.', name='Marcus Bell', role='Experiential Director', company='Vantage Motors', industry='Automotive', ctx='AutoVision International - double-decker'),
    dict(q='The rental kit looked far more premium than we expected and we reused it at two more shows. Easily our best value marketing spend last year.', name='Aisha Khan', role='Co-founder', company='Kite Labs', industry='Technology', ctx='Launchpad Startup Summit - 20 × 10 ft inline'),
]

TEAM = [
    ('Elena Marsh', 'Founder & Creative Director', 'EM'), ('Daniel Okafor', 'Head of Design', 'DO'), ('Sofia Lindqvist', 'Senior Project Manager', 'SL'),
    ('Rahul Menon', 'Workshop Director', 'RM'), ('Grace Tanaka', 'Installation Lead', 'GT'), ('Tomas Herrera', 'Lighting & AV Lead', 'TH'),
]

FAQ = [
    ('How far ahead should I start planning my stand?', 'For a custom island or larger, 16 to 20 weeks before the show is comfortable. Inline and rental stands can be ready in 6 to 8 weeks. We can work to tighter deadlines when necessary, but options narrow.'),
    ('Do you handle the hall paperwork and show-kit forms?', 'Yes. We handle stand approval drawings, power and rigging orders, insurance certificates and labour bookings on your behalf, and we track the organiser deadlines.'),
    ('Can I reuse a custom stand at future shows?', 'Most of our custom builds are modular. We can store, refurbish and reconfigure them for a new footprint, which typically costs 30 to 50 percent less than a new build.'),
    ('Do you build outside the United States?', 'Yes. We work with vetted partner crews and venue-approved contractors in North America, Europe and the Middle East, supervised by one of our project managers.'),
    ('What is included in your fixed quote?', 'Design, fabrication, graphics, shipping, installation, dismantling and project management are all itemised. Hall-controlled charges such as power, rigging and drayage are listed as estimates and billed at cost.'),
]

BLOG_CATS = [('all', 'All'), ('design', 'Design'), ('planning', 'Planning'), ('budget', 'Budget'), ('trends', 'Trends'), ('tips', 'Tips')]

POSTS = [
    dict(slug='how-to-design-a-high-impact-trade-show-booth', n=1, cat='design', title='How to Design a High-Impact Trade Show Booth', date='2026-08-12', read=7, author='Daniel Okafor',
         excerpt='Great booths do three things in the first three seconds: say who you are, show what you do and invite people in. Here is how to design for that.',
         sections=[('Start with one message', 'Visitors walk past hundreds of stands. Pick one headline that a person can read from 20 feet and put it where the aisle traffic actually looks: about 8 to 12 feet up and on the corner where people approach.'),
                   ('Design the flow before the walls', 'Draw the route you want a visitor to take: entry, discovery, conversation and exit. Keep the first 5 feet free of furniture and put your product or hero object at the natural stopping point.'),
                   ('Use light and height to add drama', 'A hanging sign, a ring truss or a tall totem lets you be seen across the hall. Balance it with a warm, welcoming ground level with proper conversation areas.')]),
    dict(slug='custom-booth-vs-rental-stand', n=2, cat='planning', title='Custom Booth vs Rental Stand: Which One Should You Choose?', date='2026-07-28', read=6, author='Sofia Lindqvist',
         excerpt='Custom builds give you total freedom; rentals give you speed and flexibility. We compare cost, lead time, branding control and sustainability.',
         sections=[('When custom makes sense', 'If you exhibit at the same shows every year, need unusual structures such as a double-decker, or have strict brand guidelines, a custom build gives you full control and a stand that can be reconfigured for years.'),
                   ('When rental wins', 'If you exhibit once or twice a year, change footprints often or have less than 10 weeks, a rental stand with custom graphics can look premium at a much lower up-front cost.'),
                   ('The hybrid option', 'Many clients now combine a rental structure with a custom counter and fascia. You get a signature element for less, and you only store what you will actually reuse.')]),
    dict(slug='how-much-does-an-exhibition-stand-cost', n=3, cat='budget', title='How Much Does an Exhibition Stand Cost? A 2026 Guide', date='2026-09-02', read=9, author='Elena Marsh',
         excerpt='Prices range from a few thousand dollars for a rental inline to six figures for a custom double-decker. Here is what actually drives the number.',
         sections=[('The short answer', 'A 10 × 10 rental inline stand starts around $4,200. A custom 20 × 20 island typically falls between $58,000 and $92,000. Double-decker and large pavilion builds start above $150,000. These are demonstration ranges; your quote depends on the factors below.'),
                   ('What drives cost', 'Booth size is the biggest driver, followed by design complexity, materials, graphics, lighting, furniture, technology and installation. Show location matters too: labour rules and freight vary widely between venues.'),
                   ('Where to save', 'Simplify the structure before you simplify the graphics. Reuse structural elements across shows, choose a hybrid rental and custom approach, and lock the design early to avoid rush charges.'),
                   ('Hidden costs to budget for', 'Hall-controlled services such as electricity, rigging, drayage and cleaning are billed separately by the organiser and often add 15 to 25 percent to the total show cost. Ask for these early.')]),
    dict(slug='trade-show-booth-design-trends', n=4, cat='trends', title='Trade Show Booth Design Trends to Watch in 2026', date='2026-06-19', read=6, author='Daniel Okafor',
         excerpt='Sustainability, calmer spaces and integrated technology are reshaping exhibition design. Here is what we are seeing on the show floor.',
         sections=[('Circular, reusable builds', 'Clients increasingly ask how much of a stand returns to stock after the show. Modular structures, FSC timber and rental systems are becoming the default.'),
                   ('Quieter, calmer environments', 'After years of high-volume LED walls, visitors are responding to acoustically treated meeting spaces and softer lighting.'),
                   ('Technology that supports conversations', 'Badge scanning, interactive displays and live data demos are most effective when they help a person start a conversation instead of replacing it.')]),
    dict(slug='how-to-prepare-for-an-exhibition', n=5, cat='planning', title='How to Prepare for an Exhibition: A 16-Week Checklist', date='2026-05-30', read=8, author='Sofia Lindqvist',
         excerpt='A week-by-week plan from booking the space to packing the last crate, with the deadlines organisers do not always highlight.',
         sections=[('Weeks 16 to 12: goals and design', 'Confirm objectives and budget, book the space, brief your stand designer and start on your show-kit forms. Get hall rules for height, structure and materials early.'),
                   ('Weeks 12 to 6: approval and build', 'Approve the design, place graphic and furniture orders and submit power and rigging requests. Book travel and staffing.'),
                   ('Weeks 6 to 0: logistics and training', 'Confirm freight, brief your booth staff on goals and conversations, and run a final artwork and lighting check before shipping.')]),
    dict(slug='exhibition-lighting-ideas', n=6, cat='design', title='Exhibition Lighting Ideas That Make Products Look Better', date='2026-05-12', read=5, author='Tomas Herrera',
         excerpt='Hall lighting is designed for safety, not for your product. Use layers, contrast and colour temperature to make your stand feel intentional.',
         sections=[('Layer your light', 'Combine ambient light for comfort, task light on products and accent light on your brand. A stand with only one layer feels flat.'),
                   ('Mind the colour temperature', 'Warm light, around 3000 K, feels welcoming; 4000 to 5000 K makes products look crisp. Mix them on purpose, not by accident.'),
                   ('Keep the power plan honest', 'Feature lighting uses more power than you expect. Include it in your hall power order from the start.')]),
    dict(slug='common-booth-design-mistakes', n=7, cat='design', title='Seven Common Booth Design Mistakes and How to Avoid Them', date='2026-04-22', read=6, author='Daniel Okafor',
         excerpt='Too much text, too many products and not enough space to talk. These are the errors we see most often, and simple ways to fix them.',
         sections=[('Trying to say everything', 'A stand with five headlines has none. Pick one message, then support it with one or two proof points.'),
                   ('Blocking the entrance', 'Counters and furniture in the first few feet create a barrier. Pull them back so people can step in without feeling committed.'),
                   ('Forgetting storage and staff comfort', 'Plan somewhere for coats, bags and a place to sit. A tired team gives worse conversations.')]),
    dict(slug='maximize-small-booth-spaces', n=8, cat='tips', title='How to Maximise Small Booth Spaces', date='2026-03-15', read=5, author='Elena Marsh',
         excerpt='A 10 × 10 stand can still be memorable. Focus on height, edges and one bold interaction.',
         sections=[('Go vertical', 'Use tall graphics, a banner and a hanging element (where allowed) so your stand is seen over the crowd.'),
                   ('Edit your product mix', 'Show three products well instead of ten badly. Store the rest and bring it out on request.'),
                   ('Leave room to talk', 'Aim for at least a third of the floor free. Empty space is the feature that invites people in.')]),
]
for p in POSTS:
    p['img'] = 'blog-%02d' % p['n']
    p['catLabel'] = dict(BLOG_CATS)[p['cat']]

ADMIN_ENQUIRIES = [
    ('ENQ-2417', 'Priya Raman', 'NovaTech Systems', 'Island 40 × 30', 'TechForward Expo', 'New', '$174k - $276k'),
    ('ENQ-2416', 'Lukas Weber', 'Meridian Health', 'Pavilion 60 × 40', 'MedLink Congress', 'Quoted', '$408k - $624k'),
    ('ENQ-2415', 'Marcus Bell', 'Vantage Motors', 'Double-decker 50 × 40', 'AutoVision', 'In review', '$340k - $520k'),
    ('ENQ-2414', 'Aisha Khan', 'Kite Labs', 'Inline 20 × 10 rental', 'Launchpad Summit', 'Won', '$8k - $14k'),
    ('ENQ-2413', 'Jonas Ekberg', 'Nordic Collective', 'Pavilion 40 × 30 rental', 'Nordic Design Week', 'Quoted', '$72k - $110k'),
    ('ENQ-2412', 'Hannah Ross', 'Curalis', 'Inline 10 × 20 rental', 'Clinical Forum', 'New', '$8k - $14k'),
    ('ENQ-2411', 'Miguel Alvarez', 'Torque EV', 'Island 40 × 40', 'Electric Mobility Show', 'In review', '$232k - $368k'),
    ('ENQ-2410', 'Chloe Martin', 'Harvest & Hearth', 'Peninsula 30 × 20', 'FoodTech Expo', 'Lost', '$75k - $114k'),
]
