# -*- coding: utf-8 -*-
import json
from layout import *
from pages_a import frame, P, PN

PB = {p['slug']: p for p in POSTS}


def blog():
    fp = PB['how-much-does-an-exhibition-stand-cost']
    o = [page_hero([('Blog', None)], 'Exhibition insights', 'Practical advice for exhibitors.',
                   'Cost guides, design ideas and planning checklists from the designers, fabricators and project managers who build stands every week.',
                   frame(img('hero-booth', 'Custom exhibition stand on a busy show floor', 800, 500, eager=True)), '')]
    o.append('<section class="section section--tight" aria-labelledby="bl-t"><div class="container" data-blog data-page-size="6"><h2 id="bl-t" class="sr-only">Articles</h2>')
    o.append('<article class="featured reveal" data-featured><a class="featured__media" href="blog-details.html?post=%s" tabindex="-1" aria-hidden="true">%s</a><div class="featured__body"><p class="bcard__meta"><span class="badge badge--accent">Featured</span><span class="badge">%s</span><time datetime="%s">%s</time><span>%d min read</span></p><h3 class="featured__title"><a href="blog-details.html?post=%s">%s</a></h3><p>%s</p>%s</div></article>'
             % (fp['slug'], img(fp['img'], fp['title'], 800, 500, sizes='(min-width:1024px) 50vw, 100vw'), fp['catLabel'], fp['date'], fmt_date(fp['date']), fp['read'], fp['slug'], fp['title'], esc(fp['excerpt']), btn('Read the Guide', 'blog-details.html?post=' + fp['slug'], 'btn--dark')))
    o.append('<div class="filterbar" data-filterbar><div class="chips" role="group" aria-label="Filter by category">%s</div><div class="filterbar__row"><div class="field field--grow"><label class="field__label" for="bl-search">Search articles</label><div class="search">%s<input class="input" id="bl-search" type="search" placeholder="Try &quot;cost&quot;, &quot;lighting&quot; or &quot;small booth&quot;" autocomplete="off" data-search></div></div><button class="btn btn--outline btn--sm" type="button" data-reset>Reset</button></div><p class="filterbar__count" role="status" aria-live="polite" data-result-count>Showing all articles</p></div>'
             % (''.join('<button class="chip" type="button" data-filter="%s" aria-pressed="%s">%s</button>' % (v, 'true' if v == 'all' else 'false', l) for v, l in BLOG_CATS), ic('search')))
    o.append('<div class="bgrid" data-grid>%s</div><div class="empty" data-empty hidden><h3>No articles found.</h3><p>Try another keyword or category.</p><button class="btn btn--dark btn--sm" type="button" data-reset>Reset</button></div><div class="load-more"><button class="btn btn--outline" type="button" data-load-more><span>Load more articles</span>%s</button></div></div></section>'
             % (''.join(post_card(p).replace('data-post', 'data-is-featured data-post', 1) if p['slug'] == fp['slug'] else post_card(p) for p in POSTS), ic('plus')))
    o.append(cta_band('Have a question we have not covered?', 'Our designers and project managers are happy to talk through your show, no obligation.', ('Ask a Designer', 'contact.html#enquiry'), ('See pricing', 'pricing.html')))
    return '\n'.join(o)


ARTICLE = '''<p class="lead">Ask five exhibitors what their stand cost and you will get five very different answers. That is not because anyone is guessing. An exhibition stand is priced like a small building project: by footprint, by complexity and by where it is being built. This guide walks through realistic 2026 ranges and, more usefully, what sits behind them.</p>
<h2 id="short-answer">The short answer</h2>
<p>A 10 &times; 10 ft rental inline stand starts around $4,200. A custom 20 &times; 20 ft island typically lands between $58,000 and $92,000. Double-decker stands and multi-exhibitor pavilions start above $150,000. These are demonstration ranges for structure and design; graphics, lighting, furniture and installation are extra, and your own quote depends on the factors below.</p>
<h2 id="cost-drivers">The main cost drivers</h2>
<ul><li><strong>Booth size.</strong> The biggest single factor, though cost per square foot usually falls as stands get larger.</li><li><strong>Design complexity.</strong> Curves, double-height walls and hanging structures need more design and fabrication hours.</li><li><strong>Materials.</strong> Timber, aluminium, solid surface and glass all carry different costs and lifespans.</li><li><strong>Graphics.</strong> Fabric and backlit graphics cost more than direct-print panels.</li><li><strong>Lighting and technology.</strong> Feature lighting, LED walls and interactive demos add hardware, programming and power.</li><li><strong>Installation and location.</strong> Venue labour rules, freight and the number of install days vary widely between cities.</li></ul>
<blockquote class="pullquote"><p>Simplify the structure before you simplify the graphics. Walls are expensive; a great message on a simple wall is not.</p></blockquote>
<h2 id="price-ranges">Typical price ranges by booth</h2>
<div class="table-wrap" tabindex="0" role="region" aria-label="Typical price ranges"><table class="table table--stack"><caption class="sr-only">Typical price ranges by booth size</caption><thead><tr><th scope="col">Booth</th><th scope="col">Rental (per show)</th><th scope="col">Custom build</th></tr></thead><tbody>
<tr><th scope="row" data-label="Booth">10 &times; 10 inline</th><td data-label="Rental (per show)">$4,200 - $7,200</td><td data-label="Custom build">$9,500 - $15,000</td></tr>
<tr><th scope="row" data-label="Booth">10 &times; 20 inline</th><td data-label="Rental (per show)">$8,400 - $14,400</td><td data-label="Custom build">$19,000 - $30,000</td></tr>
<tr><th scope="row" data-label="Booth">20 &times; 20 island</th><td data-label="Rental (per show)">$22,000 - $34,000</td><td data-label="Custom build">$58,000 - $92,000</td></tr>
<tr><th scope="row" data-label="Booth">30 &times; 30 island</th><td data-label="Rental (per show)">$49,500 - $76,500</td><td data-label="Custom build">$130,500 - $207,000</td></tr></tbody></table></div>
<h2 id="custom-vs-rental">Custom or rental: what changes</h2>
<p>A rental stand is built from an engineered kit, so you are paying for the days you use it, not for a structure you will own. A custom stand costs more up front but can be stored and reconfigured, which typically lowers the cost per show after the second or third use. Many exhibitors now combine the two: a rental structure with a custom counter and fascia.</p>
<h2 id="hidden-costs">Costs outside the stand</h2>
<p>Hall-controlled services such as electricity, rigging, drayage, cleaning and internet are billed separately by the organiser and often add 15 to 25 percent to the total show cost. Freight to and from the venue, travel for your team and giveaways sit outside the stand budget too. Ask for the organiser&rsquo;s price list early.</p>
<h2 id="save">Where you can save without losing impact</h2>
<ul><li>Lock the design early to avoid rush fees.</li><li>Reuse structural elements across shows and change only the graphics.</li><li>Put money into two or three hero moments, not everywhere.</li><li>Choose one strong lighting feature instead of several weak ones.</li></ul>
<h2 id="quote">How to get an accurate quote</h2>
<p>Send your designer the show name and hall, the footprint and open sides, your goals, the products you need to show and your budget ceiling. With those five things you should receive a layout idea, a fixed-scope price and a schedule within about a week. You can also try our <a href="pricing.html#estimator">project estimator</a> for a quick ballpark.</p>'''


def blog_details():
    p = PB['how-much-does-an-exhibition-stand-cost']
    toc = [('short-answer', 'The short answer'), ('cost-drivers', 'The main cost drivers'), ('price-ranges', 'Typical price ranges by booth'), ('custom-vs-rental', 'Custom or rental'), ('hidden-costs', 'Costs outside the stand'), ('save', 'Where you can save'), ('quote', 'How to get an accurate quote')]
    art_ld = {'@context': 'https://schema.org', '@type': 'Article', 'headline': p['title'], 'description': p['excerpt'], 'image': [BASE + '/assets/images/blog-03.svg'], 'datePublished': p['date'], 'dateModified': p['date'],
              'author': {'@type': 'Person', 'name': p['author']}, 'publisher': {'@type': 'Organization', 'name': SITE['legal'], 'logo': {'@type': 'ImageObject', 'url': BASE + '/assets/images/logo.svg'}},
              'mainEntityOfPage': BASE + '/pages/blog-details.html?post=' + p['slug']}
    o = []
    o.append('<section class="article-head on-dark blueprint"><div class="container article-head__inner">%s<p class="bcard__meta"><span class="badge badge--accent" data-post="cat">%s</span><time datetime="%s" data-post="date">%s</time><span data-post="read">%d min read</span></p><h1 class="page-title" data-post="title">%s</h1><p class="lead" data-post="excerpt">%s</p><p class="byline"><span class="avatar" aria-hidden="true" data-post="initials">EM</span><span>By <strong data-post="author">%s</strong>, %s</span></p></div></section>'
             % (crumbs([('Blog', 'blog.html'), ('Article', None)]), p['catLabel'], p['date'], fmt_date(p['date']), p['read'], p['title'], esc(p['excerpt']), p['author'], 'Founder &amp; Creative Director'))
    o.append('<section class="section section--tight"><div class="container article-wrap"><article class="article" data-article><figure class="article__cover">%s</figure><details class="toc toc--inline" open><summary>In this article</summary><ol data-toc-inline>%s</ol></details><div class="prose" data-post-body>%s</div>'
             % (img(p['img'], 'Illustration of exhibition stand costs', 800, 500, eager=True).replace('<img ', '<img data-post-img '), ''.join('<li><a href="#%s">%s</a></li>' % t for t in toc), ARTICLE))
    o.append('<div class="article__foot"><p class="article__share-t">Share this article</p>%s</div><aside class="author-card" aria-label="About the author"><span class="avatar avatar--lg" aria-hidden="true" data-post="initials2">EM</span><div><h2>About the author</h2><p><strong data-post="author2">%s</strong> writes about exhibition strategy, design and budgeting for Standform.</p></div></aside></article>'
             % ('<ul class="share" data-share-list><li><button class="share__btn" type="button" data-share="x">%s<span>Share on X</span></button></li><li><button class="share__btn" type="button" data-share="linkedin">%s<span>LinkedIn</span></button></li><li><button class="share__btn" type="button" data-share="facebook">%s<span>Facebook</span></button></li><li><button class="share__btn" type="button" data-share="copy">%s<span>Copy link</span></button></li><li><button class="share__btn" type="button" data-share="native" hidden>%s<span>Share...</span></button></li></ul>' % (ic('x'), ic('linkedin'), ic('facebook'), ic('link'), ic('share')), p['author']))
    o.append('<aside class="article-side" aria-label="Article sidebar"><nav class="toc side-card" aria-label="Table of contents"><h2>On this page</h2><ol data-toc>%s</ol><i class="toc__progress" aria-hidden="true"><b data-read-progress></b></i></nav><div class="side-card side-card--cta"><h2>Get a project range</h2><p>Try the estimator or send us your show details.</p>%s%s</div><div class="side-card"><h2>Monthly insights</h2><p>One useful email a month. No spam.</p>%s</div></aside></div></section>'
             % (''.join('<li><a href="#%s">%s</a></li>' % t for t in toc), btn('Open Estimator', 'pricing.html#estimator', 'btn--accent btn--block'), '', newsletter('bd')))
    o.append('<section class="section section--alt" aria-labelledby="ra-t"><div class="container">%s<div class="bgrid bgrid--3" data-related-posts>%s</div></div></section>'
             % (section_head('Keep reading', 'Related articles', None, btn('All Articles', 'blog.html', 'btn--dark')).replace('<h2 class="section-title">', '<h2 class="section-title" id="ra-t">'), ''.join(post_card(x) for x in (PB['custom-booth-vs-rental-stand'], PB['how-to-prepare-for-an-exhibition'], PB['maximize-small-booth-spaces']))))
    o.append(cta_band('Get a price range and a plan within a week.', 'Share your show and footprint. A designer will send a range, a schedule and the questions that matter.', ('Request a Project Quote', 'contact.html#enquiry'), ('Read the process', 'process.html')))
    return '\n'.join(o), art_ld


def contact():
    o = [page_hero([('Contact', None)], 'Project enquiry', 'Tell us about your next exhibition.',
                   'Share the show, the footprint and the goal. A designer replies within one working day with questions, ideas and a next step.',
                   None, btn('Start the Enquiry Form', '#enquiry') + btn('Call ' + SITE['phone'], 'tel:' + SITE['phone_raw'], 'btn--outline-light', 'phone'))]
    o.append('<section class="section" aria-labelledby="ct-t"><div class="container contact"><div class="contact__info"><h2 id="ct-t" class="sr-only">Contact information</h2><ul class="info-cards">'
             '<li class="info-card reveal">%s<div><h3>Phone</h3><a href="tel:%s">%s</a></div></li><li class="info-card reveal">%s<div><h3>Email</h3><a href="mailto:%s">%s</a></div></li>'
             '<li class="info-card reveal">%s<div><h3>Office &amp; workshop</h3><address>%s</address></div></li><li class="info-card reveal">%s<div><h3>Working hours</h3><p>%s<br>Show-floor support on call during events</p></div></li></ul>'
             '<figure class="map reveal">%s<figcaption><a class="link-arrow" href="https://www.google.com/maps/dir/?api=1&amp;destination=1200+Expo+Drive+Chicago+IL+60607" target="_blank" rel="noopener noreferrer"><span>Get directions (new tab)</span>%s</a></figcaption></figure></div>'
             % (ic('phone'), SITE['phone_raw'], SITE['phone'], ic('mail'), SITE['email'], SITE['email'], ic('pin'), SITE['address'], ic('clock'), SITE['hours'], ('<!-- Google Maps: keyless interactive embed. For the Maps Embed API use '
              'https://www.google.com/maps/embed/v1/place?key=YOUR_GOOGLE_MAPS_API_KEY&amp;q=1200+Expo+Drive+Chicago+IL -->'
              '<iframe class="map__frame" src="https://maps.google.com/maps?q=1200%20Expo%20Drive%2C%20Chicago%2C%20IL%2060607&amp;z=14&amp;output=embed" '
              'title="Map showing the Standform studio at 1200 Expo Drive, Chicago" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe>'), ic('arrow-up-right')))
    svc = [('custom-design', 'Custom Booth Design'), ('rental', 'Rental Stand'), ('construction', 'Booth Construction'), ('installation', 'Installation'), ('full-service', 'Full-Service Exhibition Project')]
    typ = [('island', 'Island'), ('peninsula', 'Peninsula'), ('inline', 'Inline'), ('corner', 'Corner'), ('modular', 'Modular'), ('double-decker', 'Double-decker'), ('pavilion', 'Pavilion'), ('rental', 'Rental stand'), ('unsure', 'Not sure yet')]
    bud = [('lt10', 'Under $10,000'), ('10-25', '$10,000 - $25,000'), ('25-50', '$25,000 - $50,000'), ('50-100', '$50,000 - $100,000'), ('100-250', '$100,000 - $250,000'), ('250+', '$250,000 +'), ('unsure', 'Not sure yet')]
    tm = [('lt6', 'Under 6 weeks'), ('6-10', '6 - 10 weeks'), ('10-16', '10 - 16 weeks'), ('16+', '16+ weeks'), ('flex', 'Flexible')]
    o.append('<div class="contact__form" id="enquiry"><form class="card-form card-form--light" data-validate data-demo data-endpoint="https://formspree.io/f/your-form-id" novalidate aria-labelledby="enq-h"><h2 id="enq-h" class="card-form__title">Project enquiry form</h2><p class="card-form__sub">Fields marked <span class="req">*</span> are required.</p><div class="form-alert" role="alert" data-error hidden></div><div class="form-grid">')
    o.append(field('name', 'Full name', ac='name', ph='Jane Cooper') + field('company', 'Company name', ac='organization', ph='Acme Inc.') + field('email', 'Email', 'email', ac='email', ph='jane@company.com') + field('phone', 'Phone', 'tel', ac='tel', ph='+1 555 010 1234', extra='pattern="[0-9+()\\-\\s.]{7,}" data-msg-pattern="Enter a valid phone number."')
             + field('event', 'Event name', ph='e.g. TechForward Expo 2027') + field('location', 'Event location', ph='City, country') + field('date', 'Event date', 'date') + field('size', 'Booth size', ph='e.g. 20 x 20 ft', hint='Width x depth in feet or metres.')
             + select('type', 'Booth type', typ) + select('service', 'Service required', svc) + select('budget', 'Budget range', bud, req=False) + select('timeline', 'Project timeline', tm, req=False)
             + textarea('message', 'Tell us about the project', ph='Goals, products to show, must-have features, any hall rules we should know about...', rows=5, cls='field--full'))
    o.append('<div class="field field--full"><span class="field__label" id="up-label">Attachments <span class="opt">(optional)</span></span><div class="dropzone" data-upload data-max-files="5" data-max-mb="20" data-accept="pdf,jpg,jpeg,png,svg,ai,eps,psd"><input class="dropzone__input" type="file" id="files" name="files" multiple accept=".pdf,.jpg,.jpeg,.png,.svg,.ai,.eps,.psd" aria-labelledby="up-label" aria-describedby="up-hint up-err"><label class="dropzone__label" for="files">%s<span><strong>Drag files here</strong> or <u>browse</u> to upload</span></label>'
             '<p class="field__hint" id="up-hint">PDF, JPG, PNG, SVG, AI, EPS or PSD. Up to 5 files, 20 MB each. Demo upload: files stay in your browser.</p><ul class="file-list" data-file-list aria-live="polite"></ul><p class="field__error" id="up-err" role="alert" data-upload-error></p></div></div></div>' % ic('upload'))
    o.append('<div class="field field--check"><label class="check"><input type="checkbox" id="consent" name="consent" required data-msg-required="Please confirm so we can contact you about this enquiry."><span>I agree to be contacted about this enquiry. See our <button class="link-btn" type="button" data-legal="privacy">Privacy Policy</button>.</span></label></div>')
    o.append('<p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent btn--lg" type="submit"><span>Submit Project Enquiry</span>%s</button><p class="form-note">Demo form: connect a Formspree, Netlify or custom endpoint in <code>data-endpoint</code> before going live. Nothing is emailed in demo mode.</p></form></div></div></section>' % ic('arrow'))
    o.append(cta_band('Prefer to talk?', 'Call the studio on ' + SITE['phone'] + ' during working hours and ask for a designer.', ('Call the Studio', 'tel:' + SITE['phone_raw']), ('View Portfolio', 'portfolio.html')))
    return '\n'.join(o)


def auth_art(quote, who, imgn):
    return '<div class="auth__art on-dark blueprint" aria-hidden="true">%s<figure><blockquote><p>%s</p></blockquote><figcaption>%s</figcaption></figure></div>' % (img(imgn, '', 800, 600), quote, who)


def login():
    return ('<section class="auth"><div class="auth__panel"><div class="auth__box"><a class="logo logo--dark" href="index.html" aria-label="Standform, home"><svg class="logo__mark" aria-hidden="true" focusable="false"><use href="#i-mark"/></svg><span class="logo__word">STANDFORM</span></a>'
            '<h1 class="auth__title">Client login</h1><p class="auth__sub">Sign in to review renders, approve drawings and track your show schedule. This is a demo: any valid email and an 8+ character password will work.</p>'
            '<form data-validate data-demo data-redirect="admin-dashboard.html" novalidate aria-label="Login form"><div class="form-alert" role="alert" data-error hidden></div><div class="form-grid form-grid--1">%s'
            '<div class="field"><label class="field__label" for="l-pass">Password<span class="req" aria-hidden="true"> *</span></label><div class="input-wrap"><input class="input" id="l-pass" name="password" type="password" required minlength="8" autocomplete="current-password" data-msg-required="Enter your password." data-msg-minlength="Password must be at least 8 characters."><button class="input-wrap__btn" type="button" data-toggle-password="l-pass" aria-label="Show password" aria-pressed="false">%s</button></div></div></div>'
            '<div class="auth__row"><label class="check"><input type="checkbox" name="remember"><span>Remember me</span></label><button class="link-btn" type="button" data-modal-open="reset-modal">Forgot password?</button></div>'
            '<p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent btn--lg btn--block" type="submit"><span>Log in</span></button></form><p class="auth__alt">New to Standform? <a href="register.html">Create an account</a></p><p class="auth__alt"><a href="index.html">Back to website</a></p></div></div>%s</section>'
            '<dialog class="modal" id="reset-modal" aria-labelledby="reset-t"><form method="dialog" class="modal__close-form"><button class="icon-btn modal__close" aria-label="Close dialog">%s</button></form><h2 id="reset-t">Reset your password</h2><p>Enter your email and we will send a reset link. Demo only: no email is sent.</p>'
            '<form data-validate data-demo data-close-on-success novalidate><div class="form-grid form-grid--1">%s</div><p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent btn--block" type="submit"><span>Send reset link</span></button></form></dialog>'
            % (field('l-email', 'Email', 'email', ac='email', ph='you@company.com'), ic('eye'), auth_art('Every render, drawing and schedule in one place, and a project manager one message away.', 'Client portal preview', 'project-01'), ic('close'), field('r-email', 'Email', 'email', ac='email', ph='you@company.com')))


def register():
    return ('<section class="auth auth--reverse"><div class="auth__panel"><div class="auth__box"><a class="logo logo--dark" href="index.html" aria-label="Standform, home"><svg class="logo__mark" aria-hidden="true" focusable="false"><use href="#i-mark"/></svg><span class="logo__word">STANDFORM</span></a>'
            '<h1 class="auth__title">Create your account</h1><p class="auth__sub">Set up a client portal to follow your project. Demo only: no account is created.</p>'
            '<form data-validate data-demo novalidate aria-label="Registration form"><div class="form-alert" role="alert" data-error hidden></div><div class="form-grid form-grid--1">%s%s%s'
            '<div class="field"><label class="field__label" for="g-pass">Password<span class="req" aria-hidden="true"> *</span></label><div class="input-wrap"><input class="input" id="g-pass" name="password" type="password" required minlength="8" autocomplete="new-password" aria-describedby="g-pass-hint" data-strength data-msg-required="Create a password." data-msg-minlength="Use at least 8 characters."><button class="input-wrap__btn" type="button" data-toggle-password="g-pass" aria-label="Show password" aria-pressed="false">%s</button></div><p class="field__hint" id="g-pass-hint">At least 8 characters. Mix letters, numbers and symbols.</p><div class="strength" data-strength-meter aria-hidden="true"><i></i><i></i><i></i><i></i></div><p class="strength__label" data-strength-label aria-live="polite"></p></div>'
            '<div class="field"><label class="field__label" for="g-confirm">Confirm password<span class="req" aria-hidden="true"> *</span></label><input class="input" id="g-confirm" name="confirm" type="password" required autocomplete="new-password" data-match="g-pass" data-msg-required="Confirm your password." data-msg-match="Passwords do not match."></div></div>'
            '<div class="field field--check"><label class="check"><input type="checkbox" name="terms" required data-msg-required="You must accept the terms to continue."><span>I accept the <button class="link-btn" type="button" data-legal="terms">Terms</button> and <button class="link-btn" type="button" data-legal="privacy">Privacy Policy</button>.</span></label></div>'
            '<p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent btn--lg btn--block" type="submit"><span>Create account</span></button></form><p class="auth__alt">Already registered? <a href="login.html">Log in</a></p></div></div>%s</section>'
            % (field('g-name', 'Full name', ac='name', ph='Jane Cooper'), field('g-company', 'Company', ac='organization', ph='Acme Inc.'), field('g-email', 'Work email', 'email', ac='email', ph='jane@company.com'), ic('eye'),
               auth_art('Our stand went from render to show floor without one surprise. The portal made approvals painless.', 'Demo testimonial, Kite Labs', 'project-02')))


def not_found():
    return ('<section class="nf on-dark blueprint"><div class="container nf__inner"><div class="nf__text"><p class="stand-tag"><span>HALL 404</span><span>STAND NOT FOUND</span></p><h1 class="nf__title"><span class="nf__num">404</span>Looks Like This Page Missed the Exhibition Floor.</h1><p class="lead">The page you&rsquo;re looking for couldn&rsquo;t be found.</p>'
            '<div class="btn-row">%s%s%s</div></div><div class="nf__art" aria-hidden="true">%s</div></div></section>'
            % (btn('Back to Home', 'index.html'), btn('View Portfolio', 'portfolio.html', 'btn--outline-light'), btn('Contact Us', 'contact.html', 'btn--outline-light'), img('pattern-floorplan', '', 800, 500, eager=True)))


def coming_soon_page():
    """Standalone page with minimal chrome."""
    h = head('coming-soon', 'Coming Soon | Standform Exhibition Studio', 'Something great is being built. Our new exhibition studio website launches soon. Subscribe for launch news or contact the Standform team about your next stand.', [ORG], None)
    b = ['<body class="page-coming-soon on-dark blueprint">', '<a class="skip-link" href="#main">Skip to main content</a>', sprite()]
    b.append('<header class="cs-top container"><a class="logo" href="index.html" aria-label="Standform, home"><svg class="logo__mark" aria-hidden="true" focusable="false"><use href="#i-mark"/></svg><span class="logo__word">STANDFORM</span></a><button type="button" class="dir-toggle" data-dir-toggle aria-pressed="false" aria-label="Switch to right-to-left layout" title="Switch text direction">LTR</button><button class="icon-btn" type="button" data-theme-toggle aria-label="Switch to dark mode" aria-pressed="false">%s%s</button></header>' % (ic('sun', 'theme-sun'), ic('moon', 'theme-moon')))
    b.append('<main id="main" tabindex="-1"><section class="soon container"><div class="soon__text"><p class="stand-tag"><span>UNDER CONSTRUCTION</span><span>OPENING SOON</span></p><h1 class="display">Something Great Is <span class="text-accent">Being Built.</span></h1><p class="lead">Our new exhibition studio website is going up. Until then, the workshop is open and we are taking enquiries for the next show season.</p>'
             '<div class="countdown" data-countdown="2026-12-15T09:00:00" role="timer" aria-label="Time until launch"><div><strong data-cd="days">00</strong><span>Days</span></div><div><strong data-cd="hours">00</strong><span>Hours</span></div><div><strong data-cd="minutes">00</strong><span>Minutes</span></div><div><strong data-cd="seconds">00</strong><span>Seconds</span></div></div>'
             '<form class="newsletter newsletter--lg" data-validate data-demo novalidate aria-label="Launch notification signup"><div class="field newsletter__field"><label class="field__label" for="cs-email">Get notified at launch</label><div class="newsletter__row"><input class="input" id="cs-email" name="email" type="email" required autocomplete="email" placeholder="you@company.com" data-msg-required="Enter your email address." data-msg-type="Enter a valid email address."><button class="btn btn--accent" type="submit"><span>Notify Me</span></button></div></div><p class="form-status" role="status" aria-live="polite" data-status></p></form>'
             '<div class="btn-row">%s%s</div></div><div class="soon__art" aria-hidden="true">%s</div></section></main>' % (btn('Contact the Studio', 'contact.html#enquiry'), btn('Call ' + SITE['phone'], 'tel:' + SITE['phone_raw'], 'btn--outline-light', 'phone'), img('service-02', '', 640, 480, eager=True)))
    b.append('<footer class="soon-foot container"><ul class="social" aria-label="Social media">%s</ul><p>&copy; 2026 %s. Demo template content.</p></footer>' % (''.join('<li><a href="https://www.%s.com/" target="_blank" rel="noopener noreferrer" aria-label="%s (opens in a new tab)">%s</a></li>' % (n, l, ic(n)) for n, l in (('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('x', 'X'), ('facebook', 'Facebook'))), SITE['legal']))
    b.append('<div class="toasts" role="region" aria-label="Notifications" aria-live="polite" data-toasts></div><script src="../assets/js/main.js" defer></script><script src="../assets/js/forms.js" defer></script><script src="../assets/js/plugins/countdown.js" defer></script></body></html>')
    return h + '\n' + '\n'.join(b)


# ------------------------------------------------------------------ admin dashboard (demo, not linked in public nav)
def stat(icn, label, val, delta, up=True):
    return '<li class="kpi"><span class="kpi__icon">%s</span><div><p class="kpi__label">%s</p><p class="kpi__val">%s</p><p class="kpi__delta %s">%s</p></div></li>' % (ic(icn), label, val, 'is-up' if up else 'is-down', delta)


def badge_status(s):
    m = {'New': 'info', 'Quoted': 'warn', 'In review': 'muted', 'Won': 'ok', 'Lost': 'bad', 'Published': 'ok', 'Draft': 'muted', 'Active': 'ok', 'Invited': 'warn', 'Read': 'muted', 'Unread': 'info'}
    return '<span class="pill pill--%s">%s</span>' % (m.get(s, 'muted'), s)


def table(cols, rows, label, cls='', sortable=False):
    o = '<div class="table-wrap" tabindex="0" role="region" aria-label="%s"><table class="table table--stack %s"><caption class="sr-only">%s</caption><thead><tr>%s</tr></thead><tbody>' % (label, cls, label, ''.join('<th scope="col">%s</th>' % c for c in cols))
    for r in rows:
        o += '<tr>' + ''.join(('<th scope="row" data-label="%s">%s</th>' if i == 0 else '<td data-label="%s">%s</td>') % (cols[i], c) for i, c in enumerate(r)) + '</tr>'
    return o + '</tbody></table></div>'


def admin_dashboard():
    h = head('admin-dashboard', 'Admin Dashboard Demo | Standform', 'Demonstration admin dashboard for the Standform exhibition stand template: enquiries, projects, content, messages and analytics. Not linked from the public site.', [], None, noindex=True)
    views = [('overview', 'Overview', 'grid'), ('enquiries', 'Project Enquiries', 'inbox'), ('portfolio', 'Portfolio Projects', 'layers'), ('services', 'Services', 'hammer'), ('blog', 'Blog Posts', 'file'), ('messages', 'Messages', 'message'), ('users', 'Users', 'users'), ('settings', 'Settings', 'settings'), ('analytics', 'Analytics', 'chart')]
    b = ['<body class="page-admin">', '<a class="skip-link" href="#main">Skip to main content</a>', sprite(), '<div class="dash" data-dash>']
    b.append('<aside class="dash__side" id="dash-side" aria-label="Dashboard navigation"><a class="logo" href="index.html" aria-label="Standform, back to website"><svg class="logo__mark" aria-hidden="true" focusable="false"><use href="#i-mark"/></svg><span class="logo__word">STANDFORM</span></a><p class="dash__badge">Admin demo</p><nav aria-label="Dashboard sections"><ul>%s</ul></nav><a class="dash__back" href="index.html">%s<span>Back to website</span></a></aside>'
             % (''.join('<li><button class="dash__nav%s" type="button" data-view="%s"%s>%s<span>%s</span></button></li>' % (' is-active' if i == 0 else '', v, ' aria-current="page"' if i == 0 else '', ic(icn), l) for i, (v, l, icn) in enumerate(views)), ic('arrow')))
    b.append('<div class="dash__main"><header class="dash__top"><button class="icon-btn dash__menu" type="button" data-dash-menu aria-expanded="false" aria-controls="dash-side" aria-label="Open dashboard menu">%s</button><h1 class="dash__title" data-dash-title>Overview</h1><div class="dash__tools"><div class="search search--sm">%s<label class="sr-only" for="dash-q">Search dashboard</label><input class="input" id="dash-q" type="search" placeholder="Search..." data-dash-search></div>'
             '<button type="button" class="dir-toggle" data-dir-toggle aria-pressed="false" aria-label="Switch to right-to-left layout" title="Switch text direction">LTR</button><button class="icon-btn" type="button" data-theme-toggle aria-label="Switch to dark mode" aria-pressed="false">%s%s</button><span class="avatar" title="Signed in as Elena Marsh" role="img" aria-label="Signed in as Elena Marsh">EM</span></div></header><main id="main" tabindex="-1" class="dash__content">' % (ic('menu'), ic('search'), ic('sun', 'theme-sun'), ic('moon', 'theme-moon')))
    # overview
    b.append('<section class="view is-active" id="view-overview" data-view-panel="overview" aria-label="Overview"><ul class="kpis">%s%s%s%s%s</ul>' % (stat('inbox', 'New enquiries', '24', '+12% vs last month'), stat('briefcase', 'Active projects', '11', '+2 this week'), stat('check', 'Completed projects', '47', 'Since 2025', True), stat('clipboard', 'Pending quotes', '9', '3 due this week', False), stat('calendar', 'Upcoming events', '6', 'Next: Oct 14')))
    lbl = ','.join('W%d' % i for i in range(1, 13))
    b.append('<div class="charts"><figure class="chart card" data-chart="line" data-labels="%s" data-series="[8,11,9,14,13,17,15,19,18,22,20,24]" data-unit="enquiries"><figcaption><h2>Enquiries over time</h2><p>Last 12 weeks</p></figcaption><div class="chart__canvas"></div></figure>' % lbl)
    b.append('<figure class="chart card" data-chart="bar" data-labels="Island,Inline,Rental,Peninsula,Double-decker,Pavilion" data-series="[14,11,7,8,4,3]" data-unit="projects"><figcaption><h2>Projects by booth type</h2><p>Completed since 2025</p></figcaption><div class="chart__canvas"></div></figure>')
    b.append('<figure class="chart card" data-chart="donut" data-labels="Organic search,Referral,Trade shows,Social,Paid" data-series="[38,26,21,9,6]" data-unit="%"><figcaption><h2>Leads by source</h2><p>Share of new enquiries</p></figcaption><div class="chart__canvas"></div></figure>')
    b.append('<figure class="chart card" data-chart="hbar" data-labels="Design,Approval,Fabrication,Installation" data-series="[4,2,3,2]" data-unit="projects"><figcaption><h2>Project status</h2><p>11 active projects</p></figcaption><div class="chart__canvas"></div></figure></div>')
    b.append('<div class="tables"><section class="card" aria-labelledby="t-enq"><h2 id="t-enq">Recent enquiries</h2>%s</section>' % table(['Reference', 'Contact', 'Booth', 'Status'], [(e[0], '%s<br><small>%s</small>' % (e[1], e[2]), e[3], badge_status(e[5])) for e in ADMIN_ENQUIRIES[:5]], 'Recent enquiries'))
    b.append('<section class="card" aria-labelledby="t-req"><h2 id="t-req">Project requests</h2>%s</section>' % table(['Project', 'Stage', 'Due'], [('NovaTech island', 'Fabrication', 'Sep 30'), ('Kite rental kit', 'Approval', 'Oct 04'), ('Torque EV island', 'Design', 'Oct 18'), ('Meridian pavilion', 'Installation', 'Nov 02')], 'Project requests'))
    b.append('<section class="card" aria-labelledby="t-msg"><h2 id="t-msg">Contact messages</h2>%s</section></div></section>' % table(['From', 'Subject', 'Received'], [('Hannah Ross', 'Rental availability, Oct 12', '2 h ago'), ('Jonas Ekberg', 'Pavilion quote follow-up', 'Yesterday'), ('Chloe Martin', 'Question on lighting plan', '2 days ago'), ('Miguel Alvarez', 'Revised footprint drawing', '3 days ago')], 'Contact messages'))
    # enquiries
    b.append('<section class="view" id="view-enquiries" data-view-panel="enquiries" aria-label="Project enquiries" hidden><div class="toolbar"><div class="field field--inline"><label class="field__label" for="enq-status">Status</label><select class="input select" id="enq-status" data-filter-status><option value="">All</option><option>New</option><option>In review</option><option>Quoted</option><option>Won</option><option>Lost</option></select></div><button class="btn btn--dark btn--sm" type="button" data-toast="Export started (demo)">%s<span>Export CSV</span></button></div><div class="card" data-filter-table>%s</div></section>'
             % (ic('download'), table(['Reference', 'Contact', 'Booth', 'Event', 'Status', 'Range'], [(e[0], '%s<br><small>%s</small>' % (e[1], e[2]), e[3], e[4], badge_status(e[5]), e[6]) for e in ADMIN_ENQUIRIES], 'All project enquiries')))
    # portfolio
    b.append('<section class="view" id="view-portfolio" data-view-panel="portfolio" aria-label="Portfolio projects" hidden><div class="toolbar"><a class="btn btn--accent btn--sm" href="portfolio.html">%s<span>View public portfolio</span></a></div><div class="card" data-filter-table>%s</div></section>'
             % (ic('eye'), table(['Project', 'Type', 'Industry', 'Size', 'Status'], [(p['title'], p['typeLabel'], p['industryLabel'], p['size'], badge_status('Published')) for p in PROJECTS], 'Portfolio projects')))
    # services
    b.append('<section class="view" id="view-services" data-view-panel="services" aria-label="Services" hidden><div class="card"><ul class="switch-list">%s</ul></div></section>' % ''.join('<li><span><strong>%s</strong><br><small>%s</small></span><label class="switch"><input type="checkbox" checked data-toast-change="%s"><span class="switch__ui"></span><span class="sr-only">Show %s on the website</span></label></li>' % (s['title'], s['price'][0], s['title'], s['title']) for s in SERVICES))
    # blog
    b.append('<section class="view" id="view-blog" data-view-panel="blog" aria-label="Blog posts" hidden><div class="toolbar"><a class="btn btn--accent btn--sm" href="blog.html">%s<span>View public blog</span></a></div><div class="card" data-filter-table>%s</div></section>'
             % (ic('eye'), table(['Title', 'Category', 'Author', 'Date', 'Status'], [(p['title'], p['catLabel'], p['author'], fmt_date(p['date']), badge_status('Published')) for p in POSTS], 'Blog posts')))
    # messages
    msgs = [('Hannah Ross', 'Rental availability, Oct 12', 'Hi, is the 10 x 20 kit available for the Clinical Innovations Forum on October 12?', 'Unread'), ('Jonas Ekberg', 'Pavilion quote follow-up', 'Thanks for the quote. Can we add a fifth bay for a guest exhibitor?', 'Unread'), ('Chloe Martin', 'Question on lighting plan', 'Could you send the power schedule ahead of the hall deadline?', 'Read'), ('Miguel Alvarez', 'Revised footprint drawing', 'The organiser moved us to hall B. Updated plan attached.', 'Read')]
    b.append('<section class="view" id="view-messages" data-view-panel="messages" aria-label="Messages" hidden><ul class="msg-list card">%s</ul></section>' % ''.join('<li class="msg"><span class="avatar" aria-hidden="true">%s</span><div><p><strong>%s</strong> %s</p><p class="msg__subj">%s</p><p class="msg__body">%s</p></div><button class="btn btn--outline btn--sm" type="button" data-reply="%s">Reply</button></li>' % (m[0][0], m[0], badge_status(m[3]), m[1], m[2], m[0]) for m in msgs))
    # users
    b.append('<section class="view" id="view-users" data-view-panel="users" aria-label="Users" hidden><div class="card" data-filter-table>%s</div></section>' % table(['Name', 'Role', 'Email', 'Status'], [('Elena Marsh', 'Admin', 'elena@standform.example', badge_status('Active')), ('Daniel Okafor', 'Editor', 'daniel@standform.example', badge_status('Active')), ('Sofia Lindqvist', 'Project manager', 'sofia@standform.example', badge_status('Active')), ('Priya Raman', 'Client', 'priya@novatech.example', badge_status('Active')), ('Aisha Khan', 'Client', 'aisha@kite.example', badge_status('Invited'))], 'Users'))
    # settings
    b.append('<section class="view" id="view-settings" data-view-panel="settings" aria-label="Settings" hidden><form class="card settings" data-validate data-demo novalidate aria-label="Site settings"><div class="form-grid">%s%s</div><fieldset class="calc__group"><legend>Notifications</legend><ul class="switch-list"><li><span>New enquiry email alerts</span><label class="switch"><input type="checkbox" checked><span class="switch__ui"></span><span class="sr-only">New enquiry email alerts</span></label></li><li><span>Weekly summary report</span><label class="switch"><input type="checkbox" checked><span class="switch__ui"></span><span class="sr-only">Weekly summary report</span></label></li><li><span>Show Home 2 layout in footer</span><label class="switch"><input type="checkbox"><span class="switch__ui"></span><span class="sr-only">Show Home 2 layout in footer</span></label></li></ul></fieldset><p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent" type="submit"><span>Save settings</span></button></form></section>'
             % (field('s-name', 'Studio name', extra='value="Standform Exhibition Studio"'), field('s-email', 'Enquiry email', 'email', extra='value="hello@standform.example"')))
    # analytics
    b.append('<section class="view" id="view-analytics" data-view-panel="analytics" aria-label="Analytics" hidden><div class="charts"><figure class="chart card" data-chart="bar" data-labels="Apr,May,Jun,Jul,Aug,Sep" data-series="[3200,3900,4400,5100,5600,6300]" data-unit="visits"><figcaption><h2>Website visits</h2><p>Monthly</p></figcaption><div class="chart__canvas"></div></figure>'
             '<figure class="chart card" data-chart="hbar" data-labels="Visits,Portfolio views,Estimator runs,Enquiry starts,Enquiries sent" data-series="[6300,3100,940,410,138]" data-unit=""><figcaption><h2>Conversion funnel</h2><p>September</p></figcaption><div class="chart__canvas"></div></figure></div><div class="card"><h2>Top pages</h2>%s</div></section>'
             % table(['Page', 'Views', 'Avg. time'], [('Portfolio', '3,102', '2:48'), ('Pricing', '1,624', '3:12'), ('Home', '1,480', '1:05'), ('Blog: cost guide', '1,036', '4:21'), ('Contact', '812', '1:44')], 'Top pages'))
    b.append('</main></div></div><dialog class="modal" id="reply-modal" aria-labelledby="reply-t"><form method="dialog" class="modal__close-form"><button class="icon-btn modal__close" aria-label="Close dialog">%s</button></form><h2 id="reply-t">Reply to <span data-reply-name>contact</span></h2><form data-validate data-demo data-close-on-success novalidate><div class="form-grid form-grid--1">%s</div><p class="form-status" role="status" aria-live="polite" data-status></p><button class="btn btn--accent" type="submit"><span>Send reply</span></button></form></dialog>' % (ic('close'), textarea('reply-msg', 'Message', ph='Write your reply...', rows=5)))
    b.append('<div class="toasts" role="region" aria-label="Notifications" aria-live="polite" data-toasts></div><script src="../assets/js/main.js" defer></script><script src="../assets/js/forms.js" defer></script><script src="../assets/js/dashboard.js" defer></script></body></html>')
    return h + '\n' + '\n'.join(b)
